// react-app/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import axios from 'axios';
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = { error: '', data: '', location: '' };
  }

  getWeather = (location) => {
    axios.get(`http://api.openweathermap.org/data/2.5/weather?APPID=19026fe429b4298c6dad54698d4559b8&units=metric&q=` + location + ',no')
      .then(res => {
        this.setState({ data: res.data, location: location })
      })
      .catch(e => {
        this.setState({ error: e, location: location })
      })
  };

  render() {
    const { error, data, location } = this.state;
    return (
      <div className="App">
        <img src={logo} className="App-logo" alt="logo" />
        <h1 className="App-title">ReactWeather</h1>
        <button className={'button'} onClick={() => this.getWeather('Oslo')}>Oslo</button>
        <button className={'button'} onClick={() => this.getWeather('Kristiansand')}>Kristiansand</button>
        <h3> {location}
          {data && <span><img alt={"icon"} src={`http://openweathermap.org/img/w/${data.weather[0].icon}.png`} />
              <br />
            {data.weather[0].description} </span>}
        </h3>
        <div className={'temp'}>
          {data && data.main.temp + "°"}
        </div>
        {error ? <div>{error.message}</div> : null}
      </div>
    );
  }
}

export default App;

// angular-app/src/app/app.component.ts
import {Component} from '@angular/core';
import axios from 'axios';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'AngularWeather';
  error = '';
  location = '';
  data = '';

  getData(location): void {
    this.location = location;
    axios.get(`http://api.openweathermap.org/data/2.5/weather?APPID=19026fe429b4298c6dad54698d4559b8&units=metric&q=` + location + ',no')
      .then(res => {
        this.data = res.data;
      })
      .catch(e => {
        this.error = e.message;
      })
  }

}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <img width="200" alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
  <h1>{{title}} </h1>

  <button class="button" (click)="getData('Oslo')">Oslo</button>
  <button class="button" (click)="getData('Kristiansand')">Kristiansand</button>
  <div>
    <h3>{{location}}
      <span *ngIf="data.weather">
      <img src="http://openweathermap.org/img/w/{{data.weather[0].icon}}.png">
      <br />
      {{data.weather[0].description}}
    </span>
    </h3>
    <div class="temp">
      {{data.main.temp}}°
    </div>
  </div>
  <div *ngIf="error"> {{error}}</div>
</div>
